# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user_data = [ [ "Brendon Ford",      [ { email: "brendon.ford@gmail.com"       }, { email: "brendon.ford@test.com"      } ] ],
              [ "Kobie Fellows",     [ { email: "kobie.fellows@gmail.com"      }, { email: "kobie.fellows@test.com"     } ] ],
              [ "Miriam Holmes",     [ { email: "miriam.holmes@gmail.com"      }, { email: "miriam.holmes@test.com"     } ] ],
              [ "Fabian Lawrence",   [ { email: "fabian.lawrence@gmail.com"    }, { email: "fabian.lawrence@test.com"   } ] ],
              [ "Harlee Shah",       [ { email: "harlee.shah@gmail.com"        }, { email: "harlee.shah@test.com"       } ] ],
              [ "Wilbur Hooper",     [ { email: "wilbur.hooper@gmail.com"      }, { email: "wilbur.hooper@test.com"     } ] ],
              [ "Alby Berg",         [ { email: "alby.berg@gmail.com"          }, { email: "alby.berg@test.com"         } ] ],
              [ "Lincoln Mckeown",   [ { email: "lincoln.mckeown@gmail.com"    }, { email: "lincoln.mckeown@test.com"   } ] ],
              [ "Gracie Farmer",     [ { email: "gracie.farmer@gmail.com"      }, { email: "gracie.farmer@test.com"     } ] ],
              [ "Aubrey Ashton",     [ { email: "aubrey.ashton@gmail.com"      }, { email: "aubrey.ashton@test.com"     } ] ],
              [ "Esmai Small",       [ { email: "esmai.small@gmail.com"        }, { email: "esmai.small@test.com"       } ] ],
              [ "Aimee Mcnally",     [ { email: "aimee.mcnally@gmail.com"      }, { email: "aimee.mcnally@test.com"     } ] ],
              [ "Louisa Hendricks",  [ { email: "louisa.hendricks@gmail.com"   }, { email: "louisa.hendricks@gtest.com" } ] ],
              [ "Katie Bryan",       [ { email: "katie.bryan@gmail.com"        } ] ],
              [ "Lacie Murillo",     [ { email: "lacie.murillo@gmail.com"      } ] ],
              [ "Keiran Mcgee",      [ { email: "keiran.mcgee@gmail.com"       } ] ],
              [ "Tehya Wilkinson",   [ { email: "tehya.wilkinson@gmail.com"    } ] ],
              [ "Felicia Strickland",[ { email: "felicia.strickland@gmail.com" } ] ],
              [ "Shayla Beasley",    [ { email: "shayla.beasley@gmail.com"     } ] ],
              [ "Ewan Marquez",      [ { email: "ewan.marquez@gmail.com"       } ] ],
              [ "Aurelia Patel",     [ { email: "aurelia.patel@gmail.com"      } ] ],
              [ "Jayce Whittington", [ { email: "jayce.whittington@gmail.com"  } ] ],
              [ "Kristie Newman",    [ { email: "kristie.newman@gmail.com"     } ] ],
              [ "Hawa Key",          [ { email: "hawa.key@gmail.com"           } ] ],
              [ "Korban Perkins",    [ { email: "korban.perkins@gmail.com"     } ] ],
              [ "Della Couch",       [ { email: "della.couch@gmail.com"        } ] ],
              [ "Ricky Cassidy",     [ { email: "ricky.cassidy@gmail.com"      } ] ],
              [ "Ruby Sharp",        [ { email: "ruby.sharp@gmail.com"         } ] ],
              [ "Sanaa Johnston",    [ { email: "sanaa.johnston@gmail.com"     } ] ],
              [ "Beyonce Chang",     [ { email: "beyonce.chang@gmail.com"      } ] ],
              [ "Aarya Pittman",     [ { email: "aarya.pittman@gmail.com"      } ] ],
              [ "Daniele Durham",    [ { email: "daniele.durham@gmail.com"     } ] ],
              [ "Charity West",      [ { email: "charity.west@gmail.com"       } ] ],
              [ "Sadiyah Yang",      [ { email: "sadiyah.yang@gmail.com"       } ] ],
              [ "Fergus Lang",       [ { email: "fergus.lang@gmail.com"        } ] ],
              [ "Rebecca Whitley",   [ { email: "rebecca.whitley@gmail.com"    } ] ],
              [ "Clarence Field",    [ { email: "clarence.field@gmail.com"     } ] ],
              [ "Zaara Nguyen",      [ { email: "zaara.nguyen@gmail.com"       } ] ],
              [ "Ezmae Foley",       [ { email: "ezmae.foley@gmail.com"        } ] ],
              [ "Lorelei Smith",     [ { email: "lorelei.smith@gmail.com"      } ] ],
              [ "Alaw Moyer",        [ { email: "alaw.moyer@gmail.com"         } ] ],
              [ "Joyce Burks",       [ { email: "joyce.burks@gmail.com"        } ] ],
              [ "Aisha Brewer",      [ { email: "aisha.brewer@gmail.com"       } ] ],
              [ "Shauna Harwood",    [ { email: "shauna.harwood@gmail.com"     } ] ],
              [ "Stefan Haynes",     [ { email: "stefan.haynes@gmail.com"      } ] ],
              [ "Neive Mays",        [ { email: "neive.mays@gmail.com"         } ] ],
              [ "Lilianna Zamora",   [ { email: "lilianna.zamora@gmail.com"    } ] ],
              [ "Olivia Osborne",    [ { email: "olivia.osborne@gmail.com"     } ] ],
              [ "Jia Stanley    ",   [ { email: "jia.stanley@gmail.com"        } ] ],
              [ "Lily Freeman",      [ { email: "lily.freeman@gmail.com"       } ] ],
              [ "Asmaa Scott",       [ { email: "asmaa.scott@gmail.com"        } ] ],
              [ "Jovan Bradley",     [ { email: "jovan.bradley@gmail.com"      } ] ],
              [ "Beatrix Macdonald", [ { email: "beatrix.macdonald@gmail.com"  } ] ],
              [ "Wilfred Costa",     [ { email: "wilfred.costa@gmail.com"      } ] ],
              [ "Janelle Dyer",      [ { email: "janelle.dyer@gmail.com"       } ] ],
              [ "Ishan Newton",      [ { email: "ishan.newton@gmail.com"       } ] ],
              [ "Dilan Barker",      [ { email: "dilan.barker@gmail.com"       } ] ],
              [ "Kaine Green",       [ { email: "kaine.green@gmail.com"        } ] ],
              [ "Monica Jennings",   [ { email: "monica.jennings@gmail.com"    } ] ],
              [ "Beulah Waller",     [ { email: "beulah.waller@gmail.com"      } ] ] ]

from = 1940.0
to   = Time.now.to_f
user_data.each{|name, emails_attributes| ::User.create!(name: name, birth_date: Time.at(from + rand * (to - from)), emails_attributes: emails_attributes)}
